version: 0.2

env:
  variables:
    WITH_NODE_VERSION: "20.12.1"  # Default value; can be overridden by CodeBuild project configuration


phases:
  install:
    runtime-versions:
      nodejs: !Sub ${WITH_NODE_VERSION}.x
    commands:
      - echo Installing dependencies...
      - yarn install

  build:
    commands:
      - echo Building the application...
      - yarn build

  post_build:
    commands:
      - echo Packaging the application...
      - zip -r build.zip *
      - echo Build complete

artifacts:
  files:
    - build.zip
  discard-paths: yes
  base-directory: .  # Ensure the base directory is correct for your project

cache:
  paths:
    - 'node_modules/**/*'
